version: '3.7'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: challenge-star-wars-api
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/:/data/db